---
title: "Wordle game"
output: 
  html_document: 
    toc: true
    toc_depth: 2
---

**Step 1. Create your own custom function**

```{r}
load_dictionary <- function(filename) {
  words <- readLines(filename)
  return(words)
}
f1 <- "https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/collins-scrabble-words-2019.txt"
f2 <- "https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/google-10000-english-usa-no-swears.txt"
valid_list <- load_dictionary(f1)
solution_list <- load_dictionary(f2)
str(valid_list)
str(solution_list)
```

**Step 2.Winnow your variable solution_list to only include words that are included in valid_list**

```{r}
load_dictionary <- function(filename) {
  words <- readLines(filename)
  return(words)
}
valid_list <- load_dictionary(f1)
solution_list <- load_dictionary(f2)
updated_solution_list <- intersect(solution_list, valid_list)
num_words_updated_solution_list <- length(updated_solution_list)
print(num_words_updated_solution_list)
```

**There are 8337 words in updated solution_list vector.**

**Step 3:Write a custom function called `pick_solution()`**

```{r}
#1.Write pick_solution function
pick_solution <- function(solution_list, word_length = 5) {
  #Remove words not of the specified length
  valid_length_words <- solution_list[nchar(solution_list) == word_length]
  #Check if there are words of the specified length
  if (length(valid_length_words) == 0) {
    stop("No words of the specified length found in solution_list.")
  }
  #2.Randomly choose a word from filtered list
  chosen_word <- sample(valid_length_words, 1)
  #3.Split the chosen word into a vector of single-character elements
  split_word <- strsplit(chosen_word, NULL)[[1]]
  return(split_word)
}
# 4.Use
solution <- pick_solution(solution_list, word_length = 6)
solution
```

**Step 4: create two more functions and play wordle**

```{r}
evaluateGuess <- function(guessVec, answerVec) {
  wordLength <- length(answerVec)
 
  resVec <- rep("-", wordLength)
 
   # first pass: * for in the word and in the correct position
  for (i in 1:wordLength) {
    if (guessVec[i] == answerVec[i]) {
      resVec[i] <- "*"
      answerVec[i] <- "-"  # mark unavailable 
    }
  }
   
  # second pass: + for in the word but in the wrong position
  for (i in 1:wordLength) {
    if (resVec[i] != "+") {
      idx <- match(guessVec[i], answerVec)
      if (!is.na(idx)) {
        resVec[i] <- "+"
        answerVec[idx] <- "-" # mark - for unavailable
      }
    }
  }
   
  resVec
}
  playGame <- function(solution, wordLength = 6, nGuesses = 6) {
 
   # select an answer
  possibleAnswers <- dictionary[nchar(dictionary) == wordLength]
  answer <- sample(possibleAnswers, 1)
  answerVec <- strsplit(answer, "")[[1]]
   
  print(paste("You have", nGuesses, "chances to guess a word of length", 
              wordLength))
   
  guessCnt <- 0
  lettersLeft <- LETTERS
  while (guessCnt < nGuesses) {
    # display "keyboard"
    print(paste(c("Letters left:", lettersLeft), collapse = " "))
     
    # read in guess
    guessCnt <- guessCnt + 1
    guess <- readline(paste0("Enter guess ", guessCnt, ": "))
    while (nchar(guess) != wordLength) {
      guess <- readline(paste0("Guess must have ", wordLength, " characters: "))
    }
    guess <- toupper(guess)
    guessVec <- strsplit(guess, "")[[1]]
     
    # evaluate guess and update keyboard
    resVec <- evaluateGuess(guessVec, answerVec)
     
    # update keyboard
    lettersLeft <- setdiff(lettersLeft, guessVec)
     
    # print result
    print(paste(strsplit(guess, "")[[1]], collapse = " "))
    print(paste(resVec, collapse = " "))
    if (all(resVec == "G")) {
      print("You won!")
      return(guessCnt)
    }
  }
  print(paste("Sorry, you lost! Answer was ", answer))
  return(guessCnt)
}

#play game
  dictionary <- read.csv("https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/collins-scrabble-words-2019.txt", header = FALSE, skip = 2)[, 1]
  
  dictionary <- read.csv("https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/google-10000-english-usa-no-swears.txt",head = FALSE)[, 1]
  
playGame(dictionary)

```

```{r setup, include = FALSE}
# Set GitHub PAT in the environment
Sys.setenv(GITHUB_PAT = "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")

```
